"""
Django settings for auroramart project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import warnings
from sklearn.exceptions import InconsistentVersionWarning
from decouple import config

# Suppress scikit-learn version warnings for pre-trained models
warnings.filterwarnings('ignore', category=InconsistentVersionWarning)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Load from .env file or environment variable
# Generate a new key with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = config('SECRET_KEY', default='django-insecure-dev-only-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']
AUTH_USER_MODEL = "accounts.Customer"


AUTHENTICATION_BACKENDS = [
    'accounts.backends.MultiUserModelBackend',  # Custom backend for Customer login
    'accounts.backends.StaffModelBackend',  # Custom backend for Staff login
    'accounts.backends.SuperuserModelBackend',  # Custom backend for Superuser login
    'django.contrib.auth.backends.ModelBackend',  # Fallback to default
]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "accounts",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "chat",
    "home",
    "products",
    "reviews", 
    "cart",
    "orders",
    "adminpanel",
    "vouchers",
    "notifications",
    "recommendations",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "auroramartproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.static",
            ],
        },
    },
]

# ASGI application is configured in auroramartproject/asgi.py
# WSGI_APPLICATION = "auroramartproject.wsgi.application"  # Removed: Using ASGI as default


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Singapore"  # GMT+8

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Login settings
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Django REST Framework settings
# Removed DRF and CORS - using vanilla Django with JsonResponse

# Business settings
TAX_RATE = 0.10
SHIPPING_COST = 10.00
FREE_SHIPPING_THRESHOLD = 100.00

# Stripe settings
# Only SECRET_KEY is required for Stripe Checkout (hosted payment page)
# PUBLIC_KEY is only needed if using Stripe Elements (embedded forms) - not needed here
# WEBHOOK_SECRET is optional - only needed for webhook verification (recommended for production)
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='sk_test_your_secret_key_here')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')  # Optional

# Rewards System settings
REWARD_THRESHOLDS = {
    1000: 100.00,
    2500: 250.00,
    5000: 500.00,
}
REWARD_VOUCHER_MIN_PURCHASE = 20.00 
REWARD_BADGES = {
    1000: {
        'name': 'Bronze Shopper',
        'color': '#CD7F32',  # Rich bronze - clearly distinguishable
        'icon': 'award',
        'description': 'Earned when you reach $1,000 in total spending'
    },
    2500: {
        'name': 'Silver Shopper',
        'color': '#A8A8A8',  # Medium silver - more visible than pure silver
        'icon': 'award',
        'description': 'Earned when you reach $2,500 in total spending'
    },
    5000: {
        'name': 'Gold Shopper',
        'color': '#FFA500',  # Vibrant gold/orange - clearly distinguishable
        'icon': 'award',
        'description': 'Earned when you reach $5,000 in total spending'
    },
}

# Dynamic Pricing settings
DYNAMIC_PRICING_ENABLED = True
DYNAMIC_PRICING_LOW_STOCK_THRESHOLD = 10  # Units
DYNAMIC_PRICING_DISCOUNT_PERCENTAGE = 15  # Percentage discount

# Email configuration
# For development: emails are printed to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Django Channels configuration
ASGI_APPLICATION = "auroramartproject.asgi.application"

# Channel layers configuration
# For development, use in-memory channel layer
# For production, use Redis: pip install channels-redis
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}